server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/drug_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 20050510nzay
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 开启定时任务（效期提醒用）
  task:
    scheduling:
      enabled: true
  # 禁用静态资源缓存（开发环境）
  web:
    resources:
      cache:
        period: 0

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# 分页插件配置（PageHelper）
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 日志配置
logging:
  level:
    com.example.drug.mapper: debug
